#!/bin/bash                                                                      
          
echo "set some file to --assume-unchanged ,please wait for seconds..."
git update-index --assume-unchanged 	rtl819x/boards/rtl8198/bsp/vmlinux.lds
git update-index --assume-unchanged 	rtl819x/boards/rtl8198/image/
git update-index --assume-unchanged 	rtl819x/boards/rtl8198/romfs/
git update-index --assume-unchanged 	rtl819x/boot.bin
git update-index --assume-unchanged 	rtl819x/boot.img
git update-index --assume-unchanged 	rtl819x/boot_nh.bin
git update-index --assume-unchanged 	rtl819x/linux-2.6.30/.missing-syscalls.d
git update-index --assume-unchanged 	rtl819x/linux-2.6.30/System.map
git update-index --assume-unchanged 	rtl819x/linux-2.6.30/arch/rlx/kernel/asm-offsets.s
git update-index --assume-unchanged 	rtl819x/linux-2.6.30/include/asm-rlx/asm-offsets.h
git update-index --assume-unchanged 	rtl819x/linux-2.6.30/include/linux/bounds.h
git update-index --assume-unchanged 	rtl819x/linux-2.6.30/include/linux/compile.h
git update-index --assume-unchanged 	rtl819x/linux-2.6.30/kernel/bounds.s
git update-index --assume-unchanged 	rtl819x/linux-2.6.30/kernel/timeconst.h
git update-index --assume-unchanged 	rtl819x/linux-2.6.30/rtkload/ld.script
git update-index --assume-unchanged 	rtl819x/linux-2.6.30/rtkload/linux.bin
git update-index --assume-unchanged 	rtl819x/linux-2.6.30/rtkload/memload-full
git update-index --assume-unchanged 	rtl819x/linux-2.6.30/rtkload/memload-partial
git update-index --assume-unchanged 	rtl819x/linux-2.6.30/rtkload/nfjrom
git update-index --assume-unchanged 	rtl819x/linux-2.6.30/rtkload/system.map
git update-index --assume-unchanged 	rtl819x/linux-2.6.30/rtkload/vmlinux_img.gz
git update-index --assume-unchanged 	rtl819x/linux-2.6.30/vmlinux
git update-index --assume-unchanged 	rtl819x/linux-2.6.30/vmlinux.32
git update-index --assume-unchanged 	rtl819x/users/bridge-utils/brctl/brctl
git update-index --assume-unchanged 	rtl819x/users/bridge-utils/brctl/brctld
git update-index --assume-unchanged 	rtl819x/users/busybox-1.19.4/.kconfig.d
git update-index --assume-unchanged 	rtl819x/users/busybox-1.19.4/.kernelrelease
git update-index --assume-unchanged 	rtl819x/users/busybox-1.19.4/applets/applet_tables
git update-index --assume-unchanged 	rtl819x/users/busybox-1.19.4/applets/usage
git update-index --assume-unchanged 	rtl819x/users/busybox-1.19.4/applets/usage_pod
git update-index --assume-unchanged 	rtl819x/users/busybox-1.19.4/busybox
git update-index --assume-unchanged 	rtl819x/users/busybox-1.19.4/busybox.links
git update-index --assume-unchanged 	rtl819x/users/busybox-1.19.4/busybox_unstripped
git update-index --assume-unchanged 	rtl819x/users/busybox-1.19.4/busybox_unstripped.map
git update-index --assume-unchanged 	rtl819x/users/busybox-1.19.4/busybox_unstripped.out
git update-index --assume-unchanged 	rtl819x/users/goahead-2.1.1/LINUX/compweb
git update-index --assume-unchanged 	rtl819x/users/goahead-2.1.1/LINUX/cvcfg-ap
git update-index --assume-unchanged 	rtl819x/users/goahead-2.1.1/LINUX/cvcfg-ap-8m
git update-index --assume-unchanged 	rtl819x/users/goahead-2.1.1/LINUX/cvcfg-gw
git update-index --assume-unchanged 	rtl819x/users/goahead-2.1.1/LINUX/cvcfg-vpn
git update-index --assume-unchanged 	rtl819x/users/goahead-2.1.1/LINUX/cvimg
git update-index --assume-unchanged 	rtl819x/users/goahead-2.1.1/LINUX/ddns_inet
git update-index --assume-unchanged 	rtl819x/users/goahead-2.1.1/LINUX/flash-gw
git update-index --assume-unchanged 	rtl819x/users/goahead-2.1.1/LINUX/mgbin
git update-index --assume-unchanged 	rtl819x/users/goahead-2.1.1/LINUX/mkramdisk
git update-index --assume-unchanged 	rtl819x/users/goahead-2.1.1/LINUX/ntp_inet
git update-index --assume-unchanged 	rtl819x/users/goahead-2.1.1/LINUX/ppp_inet
git update-index --assume-unchanged 	rtl819x/users/goahead-2.1.1/LINUX/sysconf-gw
git update-index --assume-unchanged 	rtl819x/users/goahead-2.1.1/LINUX/web_files
git update-index --assume-unchanged 	rtl819x/users/goahead-2.1.1/LINUX/webpages-gw.bin
git update-index --assume-unchanged 	rtl819x/users/goahead-2.1.1/LINUX/webs-gw
git update-index --assume-unchanged 	rtl819x/users/lsw-api/test
git update-index --assume-unchanged 	rtl819x/users/radvd-0.9.1/autom4te.cache/
git update-index --assume-unchanged 	rtl819x/users/squashfs4.0/squashfs-tools/mksquashfs
git update-index --assume-unchanged 	rtl819x/users/squashfs4.0/squashfs-tools/unsquashfs

git update-index --assume-unchanged bootcode_rtl8196c_98/.config
git update-index --assume-unchanged bootcode_rtl8196c_98/boot/Output/boot
git update-index --assume-unchanged bootcode_rtl8196c_98/boot/Output/boot.bin
git update-index --assume-unchanged bootcode_rtl8196c_98/boot/Output/boot.img
git update-index --assume-unchanged bootcode_rtl8196c_98/boot/Output/boot.nm
git update-index --assume-unchanged bootcode_rtl8196c_98/boot/Output/boot.out
git update-index --assume-unchanged bootcode_rtl8196c_98/boot/Output/boot.text
git update-index --assume-unchanged bootcode_rtl8196c_98/boot/Output/wboot.img
git update-index --assume-unchanged bootcode_rtl8196c_98/boot/Output/wboot.nm
git update-index --assume-unchanged bootcode_rtl8196c_98/boot/Output/wboot.out
git update-index --assume-unchanged bootcode_rtl8196c_98/boot/Output/wboot.text
git update-index --assume-unchanged bootcode_rtl8196c_98/boot/banner/mk_time
git update-index --assume-unchanged bootcode_rtl8196c_98/btcode/boot
git update-index --assume-unchanged bootcode_rtl8196c_98/btcode/boot.bin
git update-index --assume-unchanged bootcode_rtl8196c_98/btcode/boot.elf
git update-index --assume-unchanged bootcode_rtl8196c_98/btcode/boot.elf.txt
git update-index --assume-unchanged bootcode_rtl8196c_98/btcode/boot.img
git update-index --assume-unchanged bootcode_rtl8196c_98/btcode/boot.img.gz
git update-index --assume-unchanged bootcode_rtl8196c_98/btcode/piggy.bin
git update-index --assume-unchanged bootcode_rtl8196c_98/btcode/piggy.elf
git update-index --assume-unchanged bootcode_rtl8196c_98/btcode/piggy.elf.txt
git update-index --assume-unchanged bootcode_rtl8196c_98/btcode/system.map
git update-index --assume-unchanged rtl819x/boards/rtl8198/bsp/.irq.o.cmd
git update-index --assume-unchanged rtl819x/boards/rtl8198/bsp/.prom.o.cmd
git update-index --assume-unchanged rtl819x/boards/rtl8198/bsp/.serial.o.cmd
git update-index --assume-unchanged rtl819x/boards/rtl8198/bsp/.setup.o.cmd
git update-index --assume-unchanged rtl819x/boards/rtl8198/bsp/.timer.o.cmd
git update-index --assume-unchanged rtl819x/boards/rtl8198/bsp/.vmlinux.lds.cmd
git update-index --assume-unchanged rtl819x/boards/rtl8198/bsp/built-in.o
git update-index --assume-unchanged rtl819x/boards/rtl8198/bsp/irq.o
git update-index --assume-unchanged rtl819x/boards/rtl8198/bsp/prom.o
git update-index --assume-unchanged rtl819x/boards/rtl8198/bsp/setup.o
git update-index --assume-unchanged rtl819x/boards/rtl8198/root.bin
git update-index --assume-unchanged rtl819x/boards/rtl8198/squashfs-lzma.o
git update-index --assume-unchanged rtl819x/linux-2.6.30/.version
git update-index --assume-unchanged rtl819x/linux-2.6.30/linux
git update-index --assume-unchanged rtl819x/linux-2.6.30/rtkload/vmlinux-stripped
git update-index --assume-unchanged rtl819x/linux-2.6.30/rtkload/vmlinux_img
git update-index --assume-unchanged rtl819x/users/busybox-1.19.4/.config
git update-index --assume-unchanged rtl819x/users/busybox-1.19.4/.config.old
git update-index --assume-unchanged rtl819x/users/busybox-1.19.4/docs/BusyBox.html
git update-index --assume-unchanged rtl819x/users/busybox-1.19.4/docs/busybox.1
git update-index --assume-unchanged rtl819x/users/busybox-1.19.4/docs/busybox.net/BusyBox.html
git update-index --assume-unchanged rtl819x/users/goahead-2.1.1/.kernel_config
git update-index --assume-unchanged rtl819x/users/goahead-2.1.1/LINUX/cvcfg-8m
git update-index --assume-unchanged rtl819x/users/iptables-1.4.4/config.log

